-- MySQL Script generated by MySQL Workbench
-- Mon Aug 10 14:28:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiendadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendadb` DEFAULT CHARACTER SET utf8 ;
USE `tiendadb` ;

-- -----------------------------------------------------
-- Table `tiendadb`.`TipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`TipoDocumento` (
  `idTipoDocumento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Cliente` (
  `TipoDocumento` INT NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `celular` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`documento`),
  INDEX `fk_Cliente_TipoDocumento1_idx` (`TipoDocumento` ASC),
  CONSTRAINT `fk_Cliente_TipoDocumento1`
    FOREIGN KEY (`TipoDocumento`)
    REFERENCES `tiendadb`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`PreguntaSeguridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`PreguntaSeguridad` (
  `idPreguntaSeguridad` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idPreguntaSeguridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `idRol` INT NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Rol1_idx` (`idRol` ASC),
  UNIQUE INDEX `contrasena_UNIQUE` (`contrasena` ASC),
  CONSTRAINT `fk_Usuario_Rol`
    FOREIGN KEY (`idRol`)
    REFERENCES `tiendadb`.`Rol` (`idRol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Respuesta` (
  `idRespuesta` INT NOT NULL AUTO_INCREMENT,
  `idPreguntaSeguridad` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `respuesta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRespuesta`),
  INDEX `fk_Respuesta_PreguntaSeguridad1_idx` (`idPreguntaSeguridad` ASC),
  INDEX `fk_Respuesta_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Respuesta_PreguntaSeguridad1`
    FOREIGN KEY (`idPreguntaSeguridad`)
    REFERENCES `tiendadb`.`PreguntaSeguridad` (`idPreguntaSeguridad`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Respuesta_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `tiendadb`.`Usuario` (`idUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`UnidadMedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`UnidadMedida` (
  `idUnidadMedida` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUnidadMedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Presentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Presentacion` (
  `idPresentacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idPresentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Producto` (
  `idProducto` INT NOT NULL,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(80) NULL,
  `idCategoria` INT NOT NULL,
  `marca` INT NOT NULL,
  `idPresentacion` INT NOT NULL,
  `valorMedida` DOUBLE NOT NULL,
  `idUnidadMedida` INT NOT NULL,
  `existencia` INT NOT NULL,
  `indicaciones` VARCHAR(45) NULL,
  `contradindicaciones` VARCHAR(45) NULL,
  `fechaCaducidad` DATE NULL,
  `aplicacion` VARCHAR(45) NULL,
  `precio` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Categoria1_idx` (`idCategoria` ASC),
  INDEX `fk_Producto_UnidadMedida1_idx` (`idUnidadMedida` ASC),
  INDEX `fk_Producto_Presentacion1_idx` (`idPresentacion` ASC),
  INDEX `fk_Producto_Marca_idx` (`marca` ASC),
  CONSTRAINT `fk_Producto_Categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `tiendadb`.`Categoria` (`idCategoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Producto_UnidadMedida1`
    FOREIGN KEY (`idUnidadMedida`)
    REFERENCES `tiendadb`.`UnidadMedida` (`idUnidadMedida`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Producto_Presentacion`
    FOREIGN KEY (`idPresentacion`)
    REFERENCES `tiendadb`.`Presentacion` (`idPresentacion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Producto_Marca`
    FOREIGN KEY (`marca`)
    REFERENCES `tiendadb`.`Marca` (`idMarca`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Proveedor` (
  `documento` VARCHAR(45) NOT NULL,
  `idTipoDocumento` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NOT NULL,
  `nombreContacto` VARCHAR(45) NOT NULL,
  `diaVisita` VARCHAR(45) NULL,
  `observaciones` VARCHAR(80) NULL,
  INDEX `fk_Proveedor_TipoDocumento1_idx` (`idTipoDocumento` ASC),
  PRIMARY KEY (`documento`),
  CONSTRAINT `fk_Proveedor_TipoDocumento1`
    FOREIGN KEY (`idTipoDocumento`)
    REFERENCES `tiendadb`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Compras` (
  `idCompras` INT NOT NULL AUTO_INCREMENT,
  `documentoProveedor` VARCHAR(45) NOT NULL,
  `facturaProveedor` VARCHAR(45) NOT NULL,
  `fechaFacturaProveedor` DATE NOT NULL,
  `fechaRegistroCompra` DATE NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCompras`),
  INDEX `fk_Compras_Proveedor1_idx` (`documentoProveedor` ASC),
  CONSTRAINT `fk_Compras_Proveedor1`
    FOREIGN KEY (`documentoProveedor`)
    REFERENCES `tiendadb`.`Proveedor` (`documento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`DetalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`DetalleCompra` (
  `idDetalleCompra` INT NOT NULL,
  `idCompra` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `costoProducto` INT NOT NULL,
  `iva` INT NOT NULL,
  PRIMARY KEY (`idDetalleCompra`),
  INDEX `fk_DetalleCompra_Compras1_idx` (`idCompra` ASC),
  INDEX `fk_DetalleCompra_Producto1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_DetalleCompra_Compras1`
    FOREIGN KEY (`idCompra`)
    REFERENCES `tiendadb`.`Compras` (`idCompras`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DetalleCompra_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `tiendadb`.`Producto` (`idProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`TipoMascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`TipoMascota` (
  `idTipoMascota` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoMascota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Raza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Raza` (
  `idraza` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idraza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Mascota` (
  `idMascota` INT NOT NULL AUTO_INCREMENT,
  `idTipoMascota` INT NOT NULL,
  `nombreMascota` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  `idraza` INT NOT NULL,
  `peso` DOUBLE NULL,
  `fechaCumpleanos` DATE NULL,
  `edad` VARCHAR(20) NOT NULL,
  `observaciones` VARCHAR(45) NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idMascota`),
  INDEX `fk_Mascota_Raza1_idx` (`idraza` ASC),
  INDEX `fk_Mascota_TipoMascota1_idx` (`idTipoMascota` ASC),
  CONSTRAINT `fk_Mascota_Raza`
    FOREIGN KEY (`idraza`)
    REFERENCES `tiendadb`.`Raza` (`idraza`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mascota_TipoMascota`
    FOREIGN KEY (`idTipoMascota`)
    REFERENCES `tiendadb`.`TipoMascota` (`idTipoMascota`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`DetalleMascotaCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`DetalleMascotaCliente` (
  `idDetalleMascotaCliente` INT NOT NULL AUTO_INCREMENT,
  `idMascota` INT NOT NULL,
  `documentoCliente` VARCHAR(20) NOT NULL,
  INDEX `fk_DetalleMascotaCliente_Mascota1_idx` (`idMascota` ASC),
  PRIMARY KEY (`idDetalleMascotaCliente`),
  INDEX `fk_DetalleMascotaCliente_Cliente1_idx` (`documentoCliente` ASC),
  CONSTRAINT `fk_DetalleMascotaCliente_Mascota1`
    FOREIGN KEY (`idMascota`)
    REFERENCES `tiendadb`.`Mascota` (`idMascota`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DetalleMascotaCliente_Cliente1`
    FOREIGN KEY (`documentoCliente`)
    REFERENCES `tiendadb`.`Cliente` (`documento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`TipoServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`TipoServicio` (
  `idTipoServicio` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `nombreServicio` VARCHAR(45) NOT NULL,
  `idTipoServicio` INT NOT NULL,
  `descripcion` VARCHAR(80) NOT NULL,
  `recomendacionesPrevias` VARCHAR(80) NOT NULL,
  `recomendacionesPosteriores` VARCHAR(80) NOT NULL,
  `precio` INT NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idServicio`),
  INDEX `fk_Servicio_TipoServicio_idx` (`idTipoServicio` ASC),
  CONSTRAINT `fk_Servicio_TipoServicio`
    FOREIGN KEY (`idTipoServicio`)
    REFERENCES `tiendadb`.`TipoServicio` (`idTipoServicio`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Cita` (
  `idCita` INT NOT NULL AUTO_INCREMENT,
  `servicio` INT NOT NULL,
  `fechaCita` DATE NOT NULL,
  `HoraCita` TIME NOT NULL,
  `observaciones` VARCHAR(45) NOT NULL,
  `idEstado` INT NOT NULL,
  `precio` INT NULL,
  `documentoCliente` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCita`),
  INDEX `fk_Cita_Servicio_idx` (`servicio` ASC),
  INDEX `fk_Cita_Estado1_idx` (`idEstado` ASC),
  INDEX `fk_Cita_Cliente1_idx` (`documentoCliente` ASC),
  CONSTRAINT `fk_Cita_Servicio`
    FOREIGN KEY (`servicio`)
    REFERENCES `tiendadb`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Estado`
    FOREIGN KEY (`idEstado`)
    REFERENCES `tiendadb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Cliente1`
    FOREIGN KEY (`documentoCliente`)
    REFERENCES `tiendadb`.`Cliente` (`documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`FormaPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`FormaPago` (
  `idFormaPago` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFormaPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`DetalleVacunaMascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`DetalleVacunaMascota` (
  `idDetalleVacunaMascota` INT NOT NULL AUTO_INCREMENT,
  `idMascota` INT NOT NULL,
  `idVacuna` INT NOT NULL,
  `dosis` INT NOT NULL,
  `fechaAplicacion` DATE NOT NULL,
  `fechaProxima` DATE NOT NULL,
  `observaciones` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idDetalleVacunaMascota`),
  INDEX `fk_DetalleVacunaMascota_Mascota1_idx` (`idMascota` ASC),
  INDEX `fk_DetalleVacunaMascota_Producto_idx` (`idVacuna` ASC),
  CONSTRAINT `fk_DetalleVacunaMascota_Mascota`
    FOREIGN KEY (`idMascota`)
    REFERENCES `tiendadb`.`Mascota` (`idMascota`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DetalleVacunaMascota_Producto`
    FOREIGN KEY (`idVacuna`)
    REFERENCES `tiendadb`.`Producto` (`idProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Venta` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `vendedor` INT NOT NULL,
  `documentoCliente` VARCHAR(20) NOT NULL,
  `descuentoTotal` INT NOT NULL,
  `formaPago` INT NOT NULL,
  `nComprobante` VARCHAR(45) NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Vendedor_idx` (`vendedor` ASC),
  INDEX `fk_Factura_FormaPago_idx` (`formaPago` ASC),
  INDEX `fk_Factura_Cliente1_idx` (`documentoCliente` ASC),
  CONSTRAINT `fk_Factura_Vendedor`
    FOREIGN KEY (`vendedor`)
    REFERENCES `tiendadb`.`Usuario` (`idUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Factura_FormaPago`
    FOREIGN KEY (`formaPago`)
    REFERENCES `tiendadb`.`FormaPago` (`idFormaPago`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Factura_Cliente`
    FOREIGN KEY (`documentoCliente`)
    REFERENCES `tiendadb`.`Cliente` (`documento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`detalleventaproducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`detalleventaproducto` (
  `idDetalleproductofactura` INT NOT NULL,
  `factura` INT NOT NULL,
  `producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precioVenta` INT NOT NULL,
  PRIMARY KEY (`idDetalleproductofactura`),
  INDEX `Fk_detalleproductofactura_Producto_idx` (`producto` ASC),
  INDEX `fk_detalleproductofactura_Factura_idx` (`factura` ASC),
  CONSTRAINT `Fk_detalleproductofactura_Producto`
    FOREIGN KEY (`producto`)
    REFERENCES `tiendadb`.`Producto` (`idProducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalleproductofactura_Factura`
    FOREIGN KEY (`factura`)
    REFERENCES `tiendadb`.`Venta` (`idFactura`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Carrusel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Carrusel` (
  `idCarrusel` INT NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCarrusel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`quienesSomos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`quienesSomos` (
  `idquienesSomos` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idquienesSomos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`mision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`mision` (
  `idmision` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idmision`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`Contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`Contacto` (
  `idContacto` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`horario` (
  `idhorario` INT NOT NULL AUTO_INCREMENT,
  `diaInicio` VARCHAR(10) NOT NULL,
  `diaFin` VARCHAR(10) NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  PRIMARY KEY (`idhorario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`vision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`vision` (
  `idvision` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idvision`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendadb`.`DetalleProveedorMarca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendadb`.`DetalleProveedorMarca` (
  `idDetalleProveedorMarca` INT NOT NULL AUTO_INCREMENT,
  `documentoProveedor` VARCHAR(45) NOT NULL,
  `idMarca` INT NOT NULL,
  PRIMARY KEY (`idDetalleProveedorMarca`),
  INDEX `fk_DetalleProveedorMarca_Marca1_idx` (`idMarca` ASC),
  INDEX `fk_DetalleProveedorMarca_Proveedor1_idx` (`documentoProveedor` ASC),
  CONSTRAINT `fk_DetalleProveedorMarca_Marca1`
    FOREIGN KEY (`idMarca`)
    REFERENCES `tiendadb`.`Marca` (`idMarca`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DetalleProveedorMarca_Proveedor1`
    FOREIGN KEY (`documentoProveedor`)
    REFERENCES `tiendadb`.`Proveedor` (`documento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
